version: "3.9"
services:
  backend:
    container_name: blogger-backend
    image: blogger:a1.0
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - DEBUG=${BACKEND_DEBUG}
      - PORT=${BACKEND_PORT}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_DBNAME=${MONGO_DBNAME}
    volumes:
      - ./backend:/app

